title: "PluGeN: Multi-Label Conditional Generation From Pre-Trained Models"
authors:
  -
    author: Maciej Wołczyk,
    link: https://scholar.google.com/citations?user=f6Xi7aoAAAAJ
    affiliation: 1
  -
    author: Magdalena Proszewska,
    link: https://scholar.google.com/citations?hl=pl&amp;user=mzA-lkIAAAAJ
    affiliation: 1
  -
    author: Łukasz Maziarka,
    link: https://scholar.google.com/citations?hl=pl&amp;user=2dkp8z4AAAAJ
    affiliation: 1
  -
    author: Maciej Zięba,
    link: https://scholar.google.com/citations?user=XmOBJZYAAAAJ&amp;hl=pl
    affiliation: 2, 4
  -
    author: Patryk Wielopolski,
    link: https://scholar.google.com/citations?user=jXo8u3AAAAAJ&amp;hl=pl
    affiliation: 2
  -
    author: Rafał Kurczab,
    link: https://scholar.google.pl/citations?user=-AfmavgAAAAJ&amp;hl=en
    affiliation: 3
  -
    author: Marek Śmieja
    link: https://scholar.google.com/citations?user=MOmnpZcAAAAJ&amp;hl=pl
    affiliation: 1

affiliations:
  -
    id: 1
    name: Jagiellonian University,
  -
    id: 2
    name: Wroclaw University of Science and Technology,
  -
    id: 3
    name: Institute of Pharmacology PAS,
  -
    id: 4
    name: Tooploox

theme: jekyll-theme-cayman

content:
  paper: "https://arxiv.org/pdf/2109.09011.pdf"
  short_video: ""
  long_video: ""
  poster: ""