title: "PluGeN: Multi-Label Conditional Generation From Pre-Trained Models"
description: "[Maciej Wołczyk](https://scholar.google.com/citations?user=f6Xi7aoAAAAJ), [Magdalena Proszewska](https://scholar.google.com/citations?hl=pl&user=mzA-lkIAAAAJ), [Łukasz Maziarka](https://scholar.google.com/citations?hl=pl&user=2dkp8z4AAAAJ), [Maciej Zięba](https://scholar.google.com/citations?user=XmOBJZYAAAAJ&hl=pl), [Patryk Wielopolski](https://scholar.google.com/citations?user=jXo8u3AAAAAJ&hl=pl), [Rafał Kurczab](https://scholar.google.pl/citations?user=-AfmavgAAAAJ&hl=en), [Marek Śmieja](https://scholar.google.com/citations?user=MOmnpZcAAAAJ&hl=pl)"
theme: jekyll-theme-cayman

content:
  paper: "https://arxiv.org/pdf/2109.09011.pdf"
  short_video: ""
  long_video: ""
  poster: ""