title: "PluGeN: Multi-Label Conditional Generation From Pre-Trained Models"
description: <a href="https://scholar.google.com/citations?user=f6Xi7aoAAAAJ">Maciej Wołczyk</a>, <a href="https://scholar.google.com/citations?hl=pl&amp;user=mzA-lkIAAAAJ">Magdalena Proszewska</a>, <a href="https://scholar.google.com/citations?hl=pl&amp;user=2dkp8z4AAAAJ">Łukasz Maziarka</a>, <a href="https://scholar.google.com/citations?user=XmOBJZYAAAAJ&amp;hl=pl">Maciej Zięba</a>, <a href="https://scholar.google.com/citations?user=jXo8u3AAAAAJ&amp;hl=pl">Patryk Wielopolski</a>, <a href="https://scholar.google.pl/citations?user=-AfmavgAAAAJ&amp;hl=en">Rafał Kurczab</a>, <a href="https://scholar.google.com/citations?user=MOmnpZcAAAAJ&amp;hl=pl">Marek Śmieja</a>
theme: jekyll-theme-cayman

content:
  paper: "https://arxiv.org/pdf/2109.09011.pdf"
  short_video: ""
  long_video: ""
  poster: ""